# Generated by Django 2.0.7 on 2019-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20190109_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('CASADO(A)', 'CASADO(A)'), ('SOLTEIRO(A)', 'VIUVO(A)'), ('VIUVO(A)', 'VIUVO(A)'), ('DIVORCIADO(A)', 'DIVORCIADO(A)')], default='SOLTEIRO(A)', max_length=25, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='quadra',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Rua'),
        ),
    ]
