# Generated by Django 2.0.7 on 2019-05-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20190516_1142'),
        ('paciente', '0003_auto_20190409_1032'),
    ]

    operations = [
    ]
