# Generated by Django 2.0.7 on 2019-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20190111_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='grauParentesco',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Grau de Parentesco'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nomeFamiliar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do Familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('VIUVO(A)', 'VIUVO(A)'), ('CASADO(A)', 'CASADO(A)'), ('SOLTEIRO(A)', 'VIUVO(A)'), ('DIVORCIADO(A)', 'DIVORCIADO(A)')], default='SOLTEIRO(A)', max_length=25, null=True, verbose_name='Estado Civil'),
        ),
    ]
