# Generated by Django 2.0.7 on 2019-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20190404_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio1A',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 1A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio1B',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 1B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio2A',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 2A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio2B',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 2B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio3A',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 3A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio3B',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 3B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio4A',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 4A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoConvenio4B',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Convênio 4B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizacaoFotoPerfil',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Atualização Foto Perfil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio1A',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 1A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio1B',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 1B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio2A',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 2A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio2B',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 2B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio3A',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 3A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio3B',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 3B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio4A',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 4A'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoConvenio4B',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Convênio 4B'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoPerfil',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO(A)', 'VIUVO(A)'), ('DIVORCIADO(A)', 'DIVORCIADO(A)'), ('VIUVO(A)', 'VIUVO(A)'), ('CASADO(A)', 'CASADO(A)')], default='SOLTEIRO(A)', max_length=25, null=True, verbose_name='Estado Civil'),
        ),
    ]
