# Generated by Django 2.0.7 on 2019-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20190404_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio1A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio1B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio2A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio2B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio3A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio3B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio4A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoConvenio4B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atualizacaoFotoPerfil',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio1A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio1B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio2A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio2B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio3A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio3B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio4A',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoConvenio4B',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fotoPerfil',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('DIVORCIADO(A)', 'DIVORCIADO(A)'), ('CASADO(A)', 'CASADO(A)'), ('VIUVO(A)', 'VIUVO(A)'), ('SOLTEIRO(A)', 'VIUVO(A)')], default='SOLTEIRO(A)', max_length=25, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], default='MASCULINO', max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
