# Generated by Django 2.0.7 on 2019-04-04 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Clínica Ativa ?')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da Clínica')),
                ('senhaPadrao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Senha Padrão')),
                ('cnpj', models.CharField(blank=True, max_length=60, null=True, verbose_name='CNPJ')),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizada em')),
                ('usuarioAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControleCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nomeCompleto', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Nome Completo')),
                ('paciente_cpf', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente CPF')),
                ('paciente_sexo', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Sexo')),
                ('paciente_dataNascimento', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Data de Nascimento')),
                ('paciente_idade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Idade')),
                ('paciente_estadoCivil', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Estado Civil')),
                ('paciente_profissao', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Profissao')),
                ('paciente_observacao', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Observacao')),
                ('paciente_telefone', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Telefone')),
                ('paciente_celular', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Celular')),
                ('paciente_email', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente email')),
                ('paciente_cep', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente CEP')),
                ('paciente_numero', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Número')),
                ('paciente_rua', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Rua')),
                ('paciente_quadra', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Quadra')),
                ('paciente_bairro', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente bairro')),
                ('paciente_cidade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente cidade')),
                ('paciente_estado', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente estado')),
                ('paciente_complemento', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente complemento')),
                ('paciente_convenio', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Convenio')),
                ('paciente_convenioCarteira', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Número Carteira')),
                ('paciente_convenioValidade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Convenio Validade')),
                ('paciente_nomeFamiliar', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Nome Familiar')),
                ('paciente_grauParentesco', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Grau Parentesco')),
                ('paciente_origem', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Origem')),
                ('usuario_nomeCompleto', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Nome Completo')),
                ('usuario_email', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Email')),
                ('usuario_telefone', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Telefone')),
                ('usuario_celular', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Celular')),
                ('usuario_enderecoCompleto', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Endereço Completo')),
                ('usuario_titulo', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Título')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Título Ativo ?')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Convênio')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField(default=-1)),
                ('dataLogon', models.DateTimeField(null=True, verbose_name='Entrou em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Origem Ativa ?')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da Origem')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Título Ativo ?')),
                ('titulo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizada em')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='titulo',
            unique_together={('titulo', 'clinica')},
        ),
        migrations.AlterUniqueTogether(
            name='origem',
            unique_together={('nome', 'clinica')},
        ),
        migrations.AlterUniqueTogether(
            name='convenio',
            unique_together={('nome', 'clinica')},
        ),
    ]
