# Generated by Django 2.0.7 on 2019-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecampo',
            name='paciente_nomeCompleto',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='required', max_length=25, null=True, verbose_name='Paciente Nome Completo'),
        ),
        migrations.AlterField(
            model_name='controlecampo',
            name='usuario_nomeCompleto',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='required', max_length=25, null=True, verbose_name='Usuário Nome Completo'),
        ),
    ]
