# Generated by Django 2.0.7 on 2018-12-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoacesso',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usuariologado',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricoAcesso',
        ),
        migrations.DeleteModel(
            name='UsuarioLogado',
        ),
    ]
