# Generated by Django 2.0.7 on 2019-01-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181223_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Convênio')),
                ('numeroCarteira', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número da Carteira')),
            ],
        ),
    ]
