# Generated by Django 2.0.7 on 2019-02-12 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da Clínica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizada em')),
                ('usuarioAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
