# Generated by Django 2.0.7 on 2019-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='CNPJ'),
        ),
    ]
