# Generated by Django 2.0.7 on 2019-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clinica_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ativo',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Clínica Ativa ?'),
        ),
    ]
