# Generated by Django 2.0.7 on 2019-02-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clinica_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica'),
        ),
    ]
