# Generated by Django 2.0.7 on 2019-02-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_convenio_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='usuarioAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
