# Generated by Django 2.0.7 on 2019-02-13 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190212_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clinica'),
        ),
    ]
