# Generated by Django 2.0.7 on 2019-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190212_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
