# Generated by Django 2.0.7 on 2019-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clinica_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='senhaPadrao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Senha Padrão'),
        ),
    ]
