# Generated by Django 2.0.7 on 2019-02-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clinica_senhapadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Clínica Ativa ?')),
                ('titulo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizada em')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clinica')),
            ],
        ),
    ]
