# Generated by Django 2.0.7 on 2019-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='obrigatorio',
            field=models.BooleanField(default=False),
        ),
    ]
