# Generated by Django 2.0.7 on 2019-02-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_titulo_obrigatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulo',
            name='obrigatorio',
        ),
    ]
