# Generated by Django 2.0.7 on 2019-02-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_titulo_obrigatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulo',
            old_name='ativo',
            new_name='status',
        ),
    ]
