# Generated by Django 2.0.7 on 2019-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190227_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Nome do Título'),
        ),
    ]
