# Generated by Django 2.0.7 on 2019-03-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190307_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='titulo',
            unique_together={('titulo', 'clinica')},
        ),
    ]
