# Generated by Django 2.0.7 on 2019-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190307_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Título'),
        ),
    ]
