# Generated by Django 2.0.7 on 2019-03-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190308_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Origem Ativa ?')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da Origem')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clinica')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='origem',
            unique_together={('nome', 'clinica')},
        ),
    ]
