# Generated by Django 2.0.7 on 2019-03-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190308_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica'),
        ),
    ]
