# Generated by Django 2.0.7 on 2019-03-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190308_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nomeCompleto', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Nome Completo')),
                ('paciente_cpf', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente CPF')),
                ('paciente_sexo', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Sexo')),
                ('paciente_dataNascimento', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Data de Nascimento')),
                ('paciente_idade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Idade')),
                ('paciente_estadoCivil', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Estado Civil')),
                ('paciente_profissao', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Profissao')),
                ('paciente_observacao', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Observacao')),
                ('paciente_telefone', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Telefone')),
                ('paciente_celular', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Celular')),
                ('paciente_email', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente email')),
                ('paciente_cep', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente CEP')),
                ('paciente_numero', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Número')),
                ('paciente_rua', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Rua')),
                ('paciente_quadra', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Quadra')),
                ('paciente_bairro', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente bairro')),
                ('paciente_cidade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente cidade')),
                ('paciente_estado', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente estado')),
                ('paciente_complemento', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente complemento')),
                ('paciente_convenio', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Convenio')),
                ('paciente_numeroCarteira', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Número Carteira')),
                ('paciente_convenioValidade', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Convenio Validade')),
                ('paciente_nomeFamiliar', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Nome Familiar')),
                ('paciente_grauParentesco', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Grau Parentesco')),
                ('paciente_origem', models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Paciente Origem')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clinica')),
            ],
        ),
    ]
