# Generated by Django 2.0.7 on 2019-03-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_controlecampo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlecampo',
            old_name='paciente_numeroCarteira',
            new_name='paciente_convenioCarteira',
        ),
    ]
