# Generated by Django 2.0.7 on 2019-03-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190314_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_celular',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Celular'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_controleEstoque',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Controle de Estoque'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_controleProntuario',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Prontuário'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_email',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Email'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_enderecoCompleto',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Endereço Completo'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_nomeCompleto',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Nome Completo'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_telefone',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Telefone'),
        ),
        migrations.AddField(
            model_name='controlecampo',
            name='usuario_titulo',
            field=models.CharField(blank=True, choices=[('required', 'required'), ('no_required', 'no_required')], default='no_required', max_length=25, null=True, verbose_name='Usuário Título'),
        ),
    ]
