# Generated by Django 2.0.7 on 2019-03-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190330_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlecampo',
            name='usuario_controleEstoque',
        ),
        migrations.RemoveField(
            model_name='controlecampo',
            name='usuario_controleProntuario',
        ),
    ]
