# Generated by Django 2.0.7 on 2019-05-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
