# Generated by Django 2.0.7 on 2019-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20190515_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='paciente',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='servico',
            field=models.TextField(blank=True, null=True, verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dataFim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dataInicio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Título'),
        ),
    ]
