# Generated by Django 2.0.7 on 2019-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190516_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tempo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tempo'),
        ),
    ]
