# Generated by Django 2.0.7 on 2019-06-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='tempo',
        ),
    ]
