# Generated by Django 2.0.7 on 2019-06-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('agenda', '0005_remove_agenda_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.Usuario'),
        ),
    ]
