# Generated by Django 2.0.7 on 2019-06-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agenda_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='data',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data'),
        ),
    ]
