# Generated by Django 2.0.7 on 2019-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agenda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horaFim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horaInicio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora Início'),
        ),
    ]
