# Generated by Django 2.0.7 on 2019-06-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20190605_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Paciente'),
        ),
    ]
