# Generated by Django 2.0.7 on 2019-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20190605_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'AGENDADO'), ('CONFIRMADO', 'CONFIRMADO'), ('AGUARDANDO', 'AGUARDANDO'), ('EM ATENDIMENTO', 'EM ATENDIMENTO'), ('ATENDIDO', 'ATENDIDO')], default='AGENDADO', max_length=4, null=True, verbose_name='Status'),
        ),
    ]
