# Generated by Django 2.0.7 on 2019-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_agenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'AGENDADO'), ('CONFIRMADO', 'CONFIRMADO'), ('AGUARDANDO', 'AGUARDANDO'), ('EM ATENDIMENTO', 'EM ATENDIMENTO'), ('ATENDIDO', 'ATENDIDO')], default='AGENDADO', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
