# Generated by Django 2.0.7 on 2019-06-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20190614_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Título'),
        ),
    ]
