# Generated by Django 2.0.7 on 2019-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agenda_statuscolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='statusColor',
            field=models.CharField(blank=True, choices=[('AGENDADO', '#1079e9'), ('CONFIRMADO', '#5a821c'), ('AGUARDANDO', '#8B3A62'), ('EM ATENDIMENTO', '#00BFFF'), ('ATENDIDO', '#32CD32')], default='AGENDADO', max_length=25, null=True, verbose_name='Status Cor'),
        ),
    ]
