# Generated by Django 2.0.7 on 2019-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_auto_20190614_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'AGENDADO'), ('CONFIRMADO', 'CONFIRMADO'), ('AGUARDANDO', 'AGUARDANDO'), ('EM_ATENDIMENTO', 'EM ATENDIMENTO'), ('ATENDIDO', 'ATENDIDO'), ('NAO_ATENDIMENTO', 'NAO ATENDIMENTO')], default='AGENDADO', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
