# Generated by Django 2.0.7 on 2019-06-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_auto_20190614_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='statusColor',
            new_name='statusCor',
        ),
    ]
