# Generated by Django 2.0.7 on 2019-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_auto_20190614_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='statusCor',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(blank=True, choices=[('[AGENDADO,#1079e9]', 'AGENDADO'), ('CONFIRMADO', 'CONFIRMADO'), ('AGUARDANDO', 'AGUARDANDO'), ('EM ATENDIMENTO', 'EM ATENDIMENTO'), ('ATENDIDO', 'ATENDIDO'), ('NAO ATENDIMENTO', 'NAO ATENDIMENTO')], default='AGENDADO', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
