# Generated by Django 2.0.7 on 2019-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_auto_20190614_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
