# Generated by Django 2.0.7 on 2019-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_agenda_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horaAtendimento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de Atendimento'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horaChegada',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de Chegada'),
        ),
    ]
