# Generated by Django 2.0.7 on 2019-04-09 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('enderecoCompleto', models.CharField(blank=True, max_length=220, null=True, verbose_name='Endereço Completo')),
                ('controleEstoque', models.CharField(blank=True, choices=[('VISUALIZAR', 'VISUALIZAR'), ('NAO_VISUALIZAR', 'NAO_VISUALIZAR'), ('MOVIMENTAR', 'MOVIMENTAR'), ('CONTROLE_TOTAL', 'CONTROLE_TOTAL')], default='NAO_VISUALIZAR', max_length=25, null=True, verbose_name='Controle de Estoque')),
                ('controleProntuario', models.CharField(blank=True, choices=[('VISUALIZAR', 'VISUALIZAR'), ('NAO_VISUALIZAR', 'NAO_VISUALIZAR'), ('CONTROLE_TOTAL', 'CONTROLE_TOTAL')], default='NAO_VISUALIZAR', max_length=25, null=True, verbose_name='Controle de Prontuario')),
                ('ativo', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Usuário Ativo ?')),
                ('admin', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Usuário Administrador ?')),
                ('agendaPropria', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Usuário com Agenda Própria ?')),
                ('senhaPadraoAlterada', models.BooleanField(default=False)),
                ('funcionalidadeUsuario', models.TextField(blank=True, null=True, verbose_name='Funcionalidades')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clinica', to='core.Clinica')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Titulo', to='core.Titulo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
