# Generated by Django 2.0.7 on 2018-12-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='agendaPropria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Título'),
        ),
    ]
