# Generated by Django 2.0.7 on 2018-12-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20181223_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagemPerfil',
        ),
    ]
