# Generated by Django 2.0.7 on 2018-12-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_imagemperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='controleEstoque',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Controle de Estoque'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='controleProntuario',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Controle de Prontuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
