# Generated by Django 2.0.7 on 2018-12-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20181223_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='controleEstoque',
            field=models.CharField(blank=True, choices=[('VISUALIZAR', 'VISUALIZAR'), ('NAO_VISUALIZAR', 'NAO_VISUALIZAR'), ('MOVIMENTAR', 'MOVIMENTAR'), ('CONTROLE_TOTAL', 'CONTROLE_TOTAL')], default='NAO_VISUALIZAR', max_length=25, null=True, verbose_name='Controle de Estoque'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='controleProntuario',
            field=models.CharField(blank=True, choices=[('VISUALIZAR', 'VISUALIZAR'), ('NAO_VISUALIZAR', 'NAO_VISUALIZAR'), ('CONTROLE_TOTAL', 'CONTROLE_TOTAL')], default='NAO_VISUALIZAR', max_length=25, null=True, verbose_name='Controle de Prontuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, choices=[('MEDICO', 'MEDICO'), ('FISIOTERAPEUTA', 'FISIOTERAPEUTA'), ('ENFERMEIRO', 'ENFERMEIRO')], default='MEDICO', max_length=25, null=True, verbose_name='Título'),
        ),
    ]
