# Generated by Django 2.0.7 on 2018-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20181223_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, choices=[('MEDICO', 'MÉDICO'), ('FISIOTERAPEUTA', 'FISIOTERAPEUTA'), ('ENFERMEIRO', 'ENFERMEIRO')], default='MÉDICO', max_length=25, null=True, verbose_name='Título'),
        ),
    ]
