# Generated by Django 2.0.7 on 2018-12-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20181223_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='admin',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='agendaPropria',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=25, null=True, verbose_name='Ativo'),
        ),
    ]
