# Generated by Django 2.0.7 on 2018-12-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20181224_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='funcionalidadeUsuario',
            field=models.TextField(blank=True, null=True, verbose_name='Funcionalidades'),
        ),
    ]
