# Generated by Django 2.0.7 on 2018-12-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_enderecocompleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
