# Generated by Django 2.0.7 on 2018-12-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Email'),
        ),
    ]
