# Generated by Django 2.0.7 on 2019-02-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_usuario_clinicas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clinicas',
            new_name='clinicaAtual',
        ),
    ]
