# Generated by Django 2.0.7 on 2019-02-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190212_2338'),
        ('usuario', '0018_auto_20190212_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clinicaAtual',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='clinicas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Clinica', to='core.Clinica'),
        ),
    ]
