# Generated by Django 2.0.7 on 2019-03-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_auto_20190307_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clinica', to='core.Clinica'),
        ),
    ]
