# Generated by Django 2.0.7 on 2019-04-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Serviço Ativo ?')),
                ('nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do Serviço')),
                ('preco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Preço do Serviço')),
                ('tempo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tempo do Serviço (em minutos)')),
                ('rateio1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 1')),
                ('titulo1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 1')),
                ('tipoRateio1', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 1')),
                ('rateio2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 2')),
                ('titulo2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 2')),
                ('tipoRateio2', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 2')),
                ('rateio3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 3')),
                ('titulo3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 3')),
                ('tipoRateio3', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 3')),
                ('rateio4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 4')),
                ('titulo4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 4 ')),
                ('tipoRateio4', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 4')),
                ('rateio5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 5')),
                ('titulo5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 5')),
                ('tipoRateio5', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 5')),
                ('rateio6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 6')),
                ('titulo6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 6')),
                ('tipoRateio6', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 6')),
                ('prazoRetorno', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prazo para retorno (em dias)')),
                ('prazoValidade', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prazo Validade (em meses)')),
                ('nomeDocumento1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 1')),
                ('nomeDocumento2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 2')),
                ('nomeDocumento3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 3')),
                ('nomeDocumento4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4')),
                ('nomeDocumento5', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4')),
                ('nomeDocumento6', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4')),
                ('codeDocumento1', models.TextField(blank=True, null=True, verbose_name='Code Documento 1')),
                ('codeDocumento2', models.TextField(blank=True, null=True, verbose_name='Code Documento 2')),
                ('codeDocumento3', models.TextField(blank=True, null=True, verbose_name='Code Documento 3')),
                ('codeDocumento4', models.TextField(blank=True, null=True, verbose_name='Code Documento 4')),
                ('codeDocumento5', models.TextField(blank=True, null=True, verbose_name='Code Documento 5')),
                ('codeDocumento6', models.TextField(blank=True, null=True, verbose_name='Code Documento 6')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clinica')),
            ],
        ),
    ]
