# Generated by Django 2.0.7 on 2019-04-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=4, null=True, verbose_name='Serviço Ativo ?')),
                ('nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do Serviço')),
                ('preco', models.CharField(blank=True, max_length=5, null=True, verbose_name='Preço do Serviço')),
                ('tempo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tempo do Serviço (em minutos)')),
                ('prazoRetorno', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prazo para retorno (em dias)')),
                ('prazoValidade', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prazo Validade (em meses)')),
                ('nomeDocumento1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 1')),
                ('nomeDocumento2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 2')),
                ('nomeDocumento3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 3')),
                ('nomeDocumento4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4')),
                ('codeDocumento1', models.TextField(blank=True, null=True, verbose_name='Code Documento 1')),
                ('codeDocumento2', models.TextField(blank=True, null=True, verbose_name='Code Documento 2')),
                ('codeDocumento3', models.TextField(blank=True, null=True, verbose_name='Code Documento 3')),
                ('codeDocumento4', models.TextField(blank=True, null=True, verbose_name='Code Documento 4')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clinica')),
            ],
        ),
    ]
