# Generated by Django 2.0.7 on 2019-04-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='porcentagem',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Porcentagem'),
        ),
        migrations.AddField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preço do Serviço'),
        ),
    ]
