# Generated by Django 2.0.7 on 2019-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20190404_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='usuario',
        ),
        migrations.AddField(
            model_name='servico',
            name='quemRealiza',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Realiza ?'),
        ),
    ]
