# Generated by Django 2.0.7 on 2019-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20190404_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='especificar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Especificar'),
        ),
    ]
