# Generated by Django 2.0.7 on 2019-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_servico_especificar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='valor',
            new_name='valor2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='especificar',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='porcentagem',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quemRealiza',
        ),
        migrations.AddField(
            model_name='servico',
            name='especificar1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Especificar 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='especificar2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Especificar 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='especificar3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Especificar 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='porcentagem1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Porcentagem 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='porcentagem2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Porcentagem 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='porcentagem3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Porcentagem 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='quemRealiza1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Realiza 1 ?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='quemRealiza2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Realiza 2 ?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='quemRealiza3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Realiza 3 ?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor 3'),
        ),
    ]
