# Generated by Django 2.0.7 on 2019-04-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_auto_20190404_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='especificar1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='especificar2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='especificar3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='porcentagem1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='porcentagem2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='porcentagem3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quemRealiza1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quemRealiza2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quemRealiza3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor3',
        ),
        migrations.AddField(
            model_name='servico',
            name='codeDocumento5',
            field=models.TextField(blank=True, null=True, verbose_name='Code Documento 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='codeDocumento6',
            field=models.TextField(blank=True, null=True, verbose_name='Code Documento 6'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nomeDocumento5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nomeDocumento6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Documento 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 6'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio4',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio5',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio6',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 6'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 4 '),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 6'),
        ),
    ]
