# Generated by Django 2.0.7 on 2019-05-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_auto_20190408_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='quantSessao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantidade de Sessões'),
        ),
    ]
