# Generated by Django 2.0.7 on 2019-05-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0007_servico_quantsessao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='rateio1',
            new_name='rateio_1',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='rateio2',
            new_name='rateio_2',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='rateio3',
            new_name='rateio_3',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='rateio4',
            new_name='rateio_4',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='rateio5',
            new_name='rateio_5',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='rateio6',
            new_name='rateio_6',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio1',
            new_name='tipoRateio_1',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio2',
            new_name='tipoRateio_2',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio3',
            new_name='tipoRateio_3',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio4',
            new_name='tipoRateio_4',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio5',
            new_name='tipoRateio_5',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='tipoRateio6',
            new_name='tipoRateio_6',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo1',
            new_name='titulo_1',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo2',
            new_name='titulo_2',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo3',
            new_name='titulo_3',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo4',
            new_name='titulo_4',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo5',
            new_name='titulo_5',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='titulo6',
            new_name='titulo_6',
        ),
    ]
