# Generated by Django 2.0.7 on 2019-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0009_auto_20190522_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='rateio1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='rateio2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='rateio3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='rateio4',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='rateio5',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='rateio6',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio4',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio5',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoRateio6',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo1',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo2',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo3',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo4',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo5',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='titulo6',
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='rateio_6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rateio 6'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_4',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 4'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_5',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoRateio_6',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rateio 6'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 1'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 2'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 3'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 4 '),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 5'),
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo_6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Quem Recebe ? 6'),
        ),
    ]
