# Generated by Django 2.0.7 on 2019-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0010_auto_20190522_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento1',
            new_name='codeDocumento_1',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento2',
            new_name='codeDocumento_2',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento3',
            new_name='codeDocumento_3',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento4',
            new_name='codeDocumento_4',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento5',
            new_name='codeDocumento_5',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='codeDocumento6',
            new_name='codeDocumento_6',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento1',
            new_name='nomeDocumento_1',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento2',
            new_name='nomeDocumento_2',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento3',
            new_name='nomeDocumento_3',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento4',
            new_name='nomeDocumento_4',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento5',
            new_name='nomeDocumento_5',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomeDocumento6',
            new_name='nomeDocumento_6',
        ),
    ]
